# cython: language_level=3

# It is auto generated by CMake, don't modify it. You should modify the pxi.in file and 
# rerun python setup.py instead.

from cython.operator cimport preincrement, predecrement
from cython.operator cimport dereference as deref
from libcpp.pair cimport pair

from ._quantcalendar cimport Calendar, seconds, DatesArray, fromtimestamp, \
fromtimestamp_milli, fromtimestamp_micro, fromtimestamp_nano

cdef class PyCalendar_DatesArray:
    cdef const Calendar[DatesArray]* c_cal

    def get_tradedays_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.tradedays_iterator it = self.c_cal.tradedays.Upper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_tradedays_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.tradedays_iterator it = self.c_cal.tradedays.Lower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_tradedays_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[DatesArray.tradedays_iterator, DatesArray.tradedays_iterator] p = self.c_cal.tradedays.Between(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_tradedays_count(self, start: int, end: int) -> int:
        if (start > end):
            return 0
        cdef pair[DatesArray.tradedays_iterator, DatesArray.tradedays_iterator] p = self.c_cal.tradedays.Between(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return 0
        count = 0
        while (p.first <= p.second):
            count += 1
            preincrement(p.first)
        return count

    def get_tradeday_next(self, dt: int):
        cdef DatesArray.tradedays_iterator it = self.c_cal.tradedays.Upper(dt)
        return None if it.is_end() else deref(it).first

    def get_tradeday_last(self, dt: int):
        cdef DatesArray.tradedays_iterator it = self.c_cal.tradedays.Lower(dt)
        return None if it.is_end() else deref(it).first

    def get_month_ends_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.month_end_iterator it = self.c_cal.tradedays.MonthEndUpper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_month_ends_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.month_end_iterator it = self.c_cal.tradedays.MonthEndLower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_month_ends_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[DatesArray.month_end_iterator, DatesArray.month_end_iterator] p = self.c_cal.tradedays.MonthEndBetween(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_month_end_next(self, dt: int):
        cdef DatesArray.month_end_iterator it = self.c_cal.tradedays.MonthEndUpper(dt)
        return None if it.is_end() else deref(it).first

    def get_month_end_last(self, dt: int):
        cdef DatesArray.month_end_iterator it = self.c_cal.tradedays.MonthEndLower(dt)
        return None if it.is_end() else deref(it).first

    def get_month_begins_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.month_begin_iterator it = self.c_cal.tradedays.MonthBeginUpper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_month_begins_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.month_begin_iterator it = self.c_cal.tradedays.MonthBeginLower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_month_begins_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[DatesArray.month_begin_iterator, DatesArray.month_begin_iterator] p = self.c_cal.tradedays.MonthBeginBetween(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_month_begin_next(self, dt: int):
        cdef DatesArray.month_begin_iterator it = self.c_cal.tradedays.MonthBeginUpper(dt)
        return None if it.is_end() else deref(it).first

    def get_month_begin_last(self, dt: int):
        cdef DatesArray.month_begin_iterator it = self.c_cal.tradedays.MonthBeginLower(dt)
        return None if it.is_end() else deref(it).first

    def get_week_ends_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.week_end_iterator it = self.c_cal.tradedays.WeekEndUpper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_week_ends_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.week_end_iterator it = self.c_cal.tradedays.WeekEndLower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_week_ends_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[DatesArray.week_end_iterator, DatesArray.week_end_iterator] p = self.c_cal.tradedays.WeekEndBetween(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_week_end_next(self, dt: int):
        cdef DatesArray.week_end_iterator it = self.c_cal.tradedays.WeekEndUpper(dt)
        return None if it.is_end() else deref(it).first

    def get_week_end_last(self, dt: int):
        cdef DatesArray.week_end_iterator it = self.c_cal.tradedays.WeekEndLower(dt)
        return None if it.is_end() else deref(it).first

    def get_week_begins_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.week_begin_iterator it = self.c_cal.tradedays.WeekBeginUpper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_week_begins_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.week_begin_iterator it = self.c_cal.tradedays.WeekBeginLower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_week_begins_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[DatesArray.week_begin_iterator, DatesArray.week_begin_iterator] p = self.c_cal.tradedays.WeekBeginBetween(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_week_begin_next(self, dt: int):
        cdef DatesArray.week_begin_iterator it = self.c_cal.tradedays.WeekBeginUpper(dt)
        return None if it.is_end() else deref(it).first

    def get_week_begin_last(self, dt: int):
        cdef DatesArray.week_begin_iterator it = self.c_cal.tradedays.WeekBeginLower(dt)
        return None if it.is_end() else deref(it).first

    def get_week_days_gte(self, weekday: int, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.weekday_iterator it = self.c_cal.tradedays.WeekDayUpper(dt, weekday)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_week_days_lte(self, weekday: int, dt: int, count: int=2**32-1):
        ret = []
        cdef DatesArray.weekday_iterator it = self.c_cal.tradedays.WeekDayLower(dt, weekday)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_week_days_between(self, weekday: int, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[DatesArray.weekday_iterator, DatesArray.weekday_iterator] p = self.c_cal.tradedays.WeekDayBetween(start, end, weekday)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_week_day_next(self, weekday: int, dt: int):
        cdef DatesArray.weekday_iterator it = self.c_cal.tradedays.WeekDayUpper(dt, weekday)
        return None if it.is_end() else deref(it).first

    def get_week_day_last(self, weekday: int, dt: int):
        cdef DatesArray.weekday_iterator it = self.c_cal.tradedays.WeekDayLower(dt, weekday)
        return None if it.is_end() else deref(it).first

    def get_bartime_next(self, int interval, dt):
        if isinstance(dt, float):
            return self.c_cal.GetCurrentBartime(seconds(interval), fromtimestamp(<double>dt))
        else:
            return self.c_cal.GetCurrentBartime(seconds(interval), fromtimestamp_milli(<long long>dt))

    def get_bartimes_gte(self, int interval, start, size_t count=2**32-1):
        if isinstance(start, float):
            return self.c_cal.GetBartimes(seconds(interval), fromtimestamp(<double>start), count)
        else:
            return self.c_cal.GetBartimes(seconds(interval), fromtimestamp_milli(<long long>start), count)

    def get_bartimes_between(self, int interval, start, end):
        if isinstance(start, float):
            return self.c_cal.GetBartimes(seconds(interval), fromtimestamp(<double>start), fromtimestamp(<double>end))
        else:
            return self.c_cal.GetBartimes(seconds(interval), fromtimestamp_milli(<long long>start), fromtimestamp_milli(<long long>end))

    def get_next_open_close(self, dt):
        if isinstance(dt, float):
            return self.c_cal.GetNextOpenClose(fromtimestamp(<double>dt))
        else:
            return self.c_cal.GetNextOpenClose(fromtimestamp_milli(<long long>dt))

    def get_next_session(self, dt):
        if isinstance(dt, float):
            return self.c_cal.GetNextSession(fromtimestamp(<double>dt))
        else:
            return self.c_cal.GetNextSession(fromtimestamp_milli(<long long>dt))

    def get_sessions(self):
        return self.c_cal.GetSessions()

    def get_ordered_sessions(self):
        return self.c_cal.GetOrderedSessions()

    def get_open_close_time(self):
        return self.c_cal.GetOpenCloseTime()

    def get_timezone(self):
        return self.c_cal.GetTimezone().decode("utf8")

    def get_intervals(self):
        return self.c_cal.GetIntervals();

    def is_trading(self, dt):
        if isinstance(dt, float):
            return self.c_cal.IsTrading(fromtimestamp(<double>dt))
        else:
            return self.c_cal.IsTrading(fromtimestamp_milli(<long long>dt))

    def is_trading_day(self, dt):
        if isinstance(dt, float):
            return self.c_cal.IsTradingDay(fromtimestamp(<double>dt))
        else:
            return self.c_cal.IsTradingDay(fromtimestamp_milli(<long long>dt))

    def is_trading_time(self, dt):
        if isinstance(dt, float):
            return self.c_cal.IsTradingTime(fromtimestamp(<double>dt))
        else:
            return self.c_cal.IsTradingTime(fromtimestamp_milli(<long long>dt))

    def __str__(self) -> str:
        return self.c_cal.ToString().decode('UTF-8')
