# cython: language_level=3

# It is auto generated by CMake, don't modify it. You should modify the pxi.in file and 
# rerun python setup.py instead.

from cython.operator cimport preincrement, predecrement
from cython.operator cimport dereference as deref
from libcpp.pair cimport pair

from ._quantcalendar cimport Calendar, seconds, to_time_point, CalendarData

cdef class PyCalendar_CalendarData:
    cdef const Calendar[CalendarData]* c_cal

    def get_tradedays_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.tradedays_iterator it = self.c_cal.data.TradedaysUpper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_tradedays_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.tradedays_iterator it = self.c_cal.data.TradedaysLower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_tradedays_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[CalendarData.tradedays_iterator, CalendarData.tradedays_iterator] p = self.c_cal.data.TradedaysBetween(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_tradeday_next(self, dt: int):
        cdef CalendarData.tradedays_iterator it = self.c_cal.data.TradedaysUpper(dt)
        return None if it.is_end() else deref(it).first

    def get_tradeday_last(self, dt: int):
        cdef CalendarData.tradedays_iterator it = self.c_cal.data.TradedaysLower(dt)
        return None if it.is_end() else deref(it).first

    def get_month_ends_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.month_end_iterator it = self.c_cal.data.MonthEndUpper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_month_ends_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.month_end_iterator it = self.c_cal.data.MonthEndLower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_month_ends_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[CalendarData.month_end_iterator, CalendarData.month_end_iterator] p = self.c_cal.data.MonthEndBetween(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_month_end_next(self, dt: int):
        cdef CalendarData.month_end_iterator it = self.c_cal.data.MonthEndUpper(dt)
        return None if it.is_end() else deref(it).first

    def get_month_end_last(self, dt: int):
        cdef CalendarData.month_end_iterator it = self.c_cal.data.MonthEndLower(dt)
        return None if it.is_end() else deref(it).first

    def get_month_begins_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.month_begin_iterator it = self.c_cal.data.MonthBeginUpper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_month_begins_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.month_begin_iterator it = self.c_cal.data.MonthBeginLower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_month_begins_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[CalendarData.month_begin_iterator, CalendarData.month_begin_iterator] p = self.c_cal.data.MonthBeginBetween(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_month_begin_next(self, dt: int):
        cdef CalendarData.month_begin_iterator it = self.c_cal.data.MonthBeginUpper(dt)
        return None if it.is_end() else deref(it).first

    def get_month_begin_last(self, dt: int):
        cdef CalendarData.month_begin_iterator it = self.c_cal.data.MonthBeginLower(dt)
        return None if it.is_end() else deref(it).first

    def get_week_ends_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.week_end_iterator it = self.c_cal.data.WeekEndUpper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_week_ends_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.week_end_iterator it = self.c_cal.data.WeekEndLower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_week_ends_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[CalendarData.week_end_iterator, CalendarData.week_end_iterator] p = self.c_cal.data.WeekEndBetween(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_week_end_next(self, dt: int):
        cdef CalendarData.week_end_iterator it = self.c_cal.data.WeekEndUpper(dt)
        return None if it.is_end() else deref(it).first

    def get_week_end_last(self, dt: int):
        cdef CalendarData.week_end_iterator it = self.c_cal.data.WeekEndLower(dt)
        return None if it.is_end() else deref(it).first

    def get_week_begins_gte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.week_begin_iterator it = self.c_cal.data.WeekBeginUpper(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_week_begins_lte(self, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.week_begin_iterator it = self.c_cal.data.WeekBeginLower(dt)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_week_begins_between(self, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[CalendarData.week_begin_iterator, CalendarData.week_begin_iterator] p = self.c_cal.data.WeekBeginBetween(start, end)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_week_begin_next(self, dt: int):
        cdef CalendarData.week_begin_iterator it = self.c_cal.data.WeekBeginUpper(dt)
        return None if it.is_end() else deref(it).first

    def get_week_begin_last(self, dt: int):
        cdef CalendarData.week_begin_iterator it = self.c_cal.data.WeekBeginLower(dt)
        return None if it.is_end() else deref(it).first

    def get_week_days_gte(self, weekday: int, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.weekday_iterator it = self.c_cal.data.WeekDayUpper(dt, weekday)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_week_days_lte(self, weekday: int, dt: int, count: int=2**32-1):
        ret = []
        cdef CalendarData.weekday_iterator it = self.c_cal.data.WeekDayLower(dt, weekday)
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_week_days_between(self, weekday: int, start: int, end: int):
        ret = []
        if (start > end):
            return ret
        cdef pair[CalendarData.weekday_iterator, CalendarData.weekday_iterator] p = self.c_cal.data.WeekDayBetween(start, end, weekday)
        if (p.first.is_end() or p.second.is_end()):
            return ret
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_week_day_next(self, weekday: int, dt: int):
        cdef CalendarData.weekday_iterator it = self.c_cal.data.WeekDayUpper(dt, weekday)
        return None if it.is_end() else deref(it).first

    def get_week_day_last(self, weekday: int, dt: int):
        cdef CalendarData.weekday_iterator it = self.c_cal.data.WeekDayLower(dt, weekday)
        return None if it.is_end() else deref(it).first

    def get_bartime_next(self, interval: int, dt: float):
        return self.c_cal.GetCurrentBartime(seconds(interval), to_time_point(dt))

    def get_bartimes_gte(self, interval: int, start: float, count: int=2**32-1):
        # count must cast to <size_t>, otherwise it is PyObject* type and no suitable overloading method found.
        return self.c_cal.GetBartimes(seconds(interval), to_time_point(start), <size_t>count)

    def get_bartimes_between(self, interval: int, start: float, end: float):
        return self.c_cal.GetBartimes(seconds(interval), to_time_point(start), to_time_point(end))

    def get_next_open_close(self, dt: float):
        return self.c_cal.GetNextOpenClose(to_time_point(dt))

    def get_next_session(self, dt: float):
        return self.c_cal.GetNextSession(to_time_point(dt))

    def get_sessions(self):
        return self.c_cal.GetSessions()

    def get_ordered_sessions(self):
        return self.c_cal.GetOrderedSessions()

    def get_open_close_time(self):
        return self.c_cal.GetOpenCloseTime()

    def is_trading(self, dt: float):
        return self.c_cal.IsTrading(to_time_point(dt))

    def is_trading_day(self, dt: float):
        return self.c_cal.IsTradingDay(to_time_point(dt))

    def is_trading_time(self, dt: float):
        return self.c_cal.IsTradingTime(to_time_point(dt))

    def __str__(self) -> str:
        return self.c_cal.ToString().decode('UTF-8')
