# cython: language_level=3

# It is auto generated by CMake, don't modify it. You should modify the pxi.in file and 
# rerun python setup.py instead.

from cython.operator cimport preincrement, predecrement
from cython.operator cimport dereference as deref
from libcpp.pair cimport pair

from ._quantcalendar cimport Calendar, seconds, DatesArray, RangeClosed

cdef class PyCalendar_DatesArray:
    cdef const Calendar[DatesArray]* c_cal

    def get_tradedays_gte(self, dt, count: int=2**32-1):
        cdef DatesArray.tradedays_iterator it = self.c_cal.tradedays.Upper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_tradedays_lte(self, dt, count: int=2**32-1):
        cdef DatesArray.tradedays_iterator it = self.c_cal.tradedays.Lower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_tradedays_between(self, start, end):
        ret = []
        cdef pair[DatesArray.tradedays_iterator, DatesArray.tradedays_iterator] p = self.c_cal.tradedays.Between(to_daily(start), to_daily(end))
        if (p.first.is_end() or p.second.is_end()):
            raise IndexError(f"{start} - {end} is out of calendar, update it please.")
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_tradedays_count(self, start, end) -> int:
        cdef pair[DatesArray.tradedays_iterator, DatesArray.tradedays_iterator] p = self.c_cal.tradedays.Between(to_daily(start), to_daily(end))
        if (p.first.is_end() or p.second.is_end()):
            raise IndexError(f"{start} - {end} is out of calendar, update it please.")
        count = 0
        while (p.first <= p.second):
            count += 1
            preincrement(p.first)
        return count

    def get_tradeday_next(self, dt):
        cdef DatesArray.tradedays_iterator it = self.c_cal.tradedays.Upper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_tradeday_last(self, dt):
        cdef DatesArray.tradedays_iterator it = self.c_cal.tradedays.Lower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_month_ends_gte(self, dt, count: int=2**32-1):
        cdef DatesArray.month_end_iterator it = self.c_cal.tradedays.MonthEndUpper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_month_ends_lte(self, dt, count: int=2**32-1):
        cdef DatesArray.month_end_iterator it = self.c_cal.tradedays.MonthEndLower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_month_ends_between(self, start, end):
        cdef pair[DatesArray.month_end_iterator, DatesArray.month_end_iterator] p = self.c_cal.tradedays.MonthEndBetween(to_daily(start), to_daily(end))
        if (p.first.is_end() or p.second.is_end()):
            raise IndexError(f"{start} - {end} is out of calendar, update it please.")
        ret = []
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_month_end_next(self, dt):
        cdef DatesArray.month_end_iterator it = self.c_cal.tradedays.MonthEndUpper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_month_end_last(self, dt):
        cdef DatesArray.month_end_iterator it = self.c_cal.tradedays.MonthEndLower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_month_begins_gte(self, dt, count: int=2**32-1):
        cdef DatesArray.month_begin_iterator it = self.c_cal.tradedays.MonthBeginUpper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_month_begins_lte(self, dt, count: int=2**32-1):
        cdef DatesArray.month_begin_iterator it = self.c_cal.tradedays.MonthBeginLower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_month_begins_between(self, start, end):
        cdef pair[DatesArray.month_begin_iterator, DatesArray.month_begin_iterator] p = self.c_cal.tradedays.MonthBeginBetween(to_daily(start), to_daily(end))
        if (p.first.is_end() or p.second.is_end()):
            raise IndexError(f"{start} - {end} is out of calendar, update it please.")
        ret = []
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_month_begin_next(self, dt):
        cdef DatesArray.month_begin_iterator it = self.c_cal.tradedays.MonthBeginUpper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_month_begin_last(self, dt):
        cdef DatesArray.month_begin_iterator it = self.c_cal.tradedays.MonthBeginLower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_week_ends_gte(self, dt, count: int=2**32-1):
        cdef DatesArray.week_end_iterator it = self.c_cal.tradedays.WeekEndUpper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_week_ends_lte(self, dt, count: int=2**32-1):
        cdef DatesArray.week_end_iterator it = self.c_cal.tradedays.WeekEndLower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_week_ends_between(self, start, end):
        cdef pair[DatesArray.week_end_iterator, DatesArray.week_end_iterator] p = self.c_cal.tradedays.WeekEndBetween(to_daily(start), to_daily(end))
        if (p.first.is_end() or p.second.is_end()):
            raise IndexError(f"{start} - {end} is out of calendar, update it please.")
        ret = []
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_week_end_next(self, dt):
        cdef DatesArray.week_end_iterator it = self.c_cal.tradedays.WeekEndUpper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_week_end_last(self, dt):
        cdef DatesArray.week_end_iterator it = self.c_cal.tradedays.WeekEndLower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_week_begins_gte(self, dt, count: int=2**32-1):
        cdef DatesArray.week_begin_iterator it = self.c_cal.tradedays.WeekBeginUpper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_week_begins_lte(self, dt, count: int=2**32-1):
        cdef DatesArray.week_begin_iterator it = self.c_cal.tradedays.WeekBeginLower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_week_begins_between(self, start, end):
        cdef pair[DatesArray.week_begin_iterator, DatesArray.week_begin_iterator] p = self.c_cal.tradedays.WeekBeginBetween(to_daily(start), to_daily(end))
        if (p.first.is_end() or p.second.is_end()):
            raise IndexError(f"{start} - {end} is out of calendar, update it please.")
        ret = []
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_week_begin_next(self, dt):
        cdef DatesArray.week_begin_iterator it = self.c_cal.tradedays.WeekBeginUpper(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_week_begin_last(self, dt):
        cdef DatesArray.week_begin_iterator it = self.c_cal.tradedays.WeekBeginLower(to_daily(dt))
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_week_days_gte(self, weekday: int, dt, count: int=2**32-1):
        cdef DatesArray.weekday_iterator it = self.c_cal.tradedays.WeekDayUpper(to_daily(dt), weekday)
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            preincrement(it)
            count -= 1
        return ret

    def get_week_days_lte(self, weekday: int, dt, count: int=2**32-1):
        cdef DatesArray.weekday_iterator it = self.c_cal.tradedays.WeekDayLower(to_daily(dt), weekday)
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        ret = []
        while not it.is_end() and count > 0:
            ret.append(deref(it).first)
            predecrement(it)
            count -= 1
        ret.reverse()
        return ret

    def get_week_days_between(self, weekday: int, start, end):
        cdef pair[DatesArray.weekday_iterator, DatesArray.weekday_iterator] p = self.c_cal.tradedays.WeekDayBetween(to_daily(start), to_daily(end), weekday)
        if (p.first.is_end() or p.second.is_end()):
            raise IndexError(f"{start} - {end} is out of calendar, update it please.")
        ret = []
        while (p.first <= p.second):
            ret.append(deref(p.first).first)
            preincrement(p.first)
        return ret

    def get_week_day_next(self, weekday: int, dt):
        cdef DatesArray.weekday_iterator it = self.c_cal.tradedays.WeekDayUpper(to_daily(dt), weekday)
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_week_day_last(self, weekday: int, dt):
        cdef DatesArray.weekday_iterator it = self.c_cal.tradedays.WeekDayLower(to_daily(dt), weekday)
        if it.is_end(): raise IndexError(f"{dt} is out of calendar, update it please.")
        return deref(it).first

    def get_bartime_next(self, int interval, dt):
        return self.c_cal.GetCurrentBartime(seconds(interval), to_timepoint(dt))

    def get_bartimes_gte(self, int interval, start, size_t count=2**32-1):
        return self.c_cal.GetBartimes(seconds(interval), to_timepoint(start), count)

    def get_bartimes_between(self, int interval, start, end):
        return self.c_cal.GetBartimes(seconds(interval), to_timepoint(start), to_timepoint(end))

    def get_next_open_close(self, dt):
        return self.c_cal.GetNextOpenClose(to_timepoint(dt))

    def get_next_session(self, dt):
        return self.c_cal.GetNextSession(to_timepoint(dt))

    def get_sessions(self):
        return self.c_cal.GetSessions()

    def get_ordered_sessions(self):
        return self.c_cal.GetOrderedSessions()

    def get_open_close_time(self):
        return self.c_cal.GetOpenCloseTime()

    def get_timezone(self):
        return self.c_cal.GetTimezone().decode("utf8")

    def get_intervals(self):
        return self.c_cal.GetIntervals()

    def is_trading(self, dt):
        return self.c_cal.IsTrading(to_timepoint(dt))

    def is_trading_day(self, dt):
        return self.c_cal.IsTradingDay(to_timepoint(dt))

    def is_trading_time(self, tm, rangeclosed: RangeClosed = RangeClosed.BOTH):
        if is_datetime64_object(tm) or PyDateTime_Check(tm):
            return self.c_cal.IsTradingTime(to_timepoint(tm), rangeclosed)
        else:
            return self.c_cal.IsTradingTime(seconds(tm), rangeclosed)

    def __str__(self) -> str:
        return self.c_cal.ToString().decode('UTF-8')
